import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Provider from '@/store/provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <Provider>
      <html lang="ko">
        <head>
          <script
            defer
            src="https://t1.kakaocdn.net/kakao_js_sdk/2.5.0/kakao.min.js"
            integrity="sha384-kYPsUbBPlktXsY6/oNHSUDZoTX6+YI51f63jCPEIPFP09ttByAdxd2mEjKuhdqn4"
            crossOrigin="anonymous"
          />
        </head>
        <body className={inter.className}>{children}</body>
      </html>
    </Provider>
  );
};

export default RootLayout;
